### ISSUE TITLE
Extract set_logger_metadata

### ISSUE THREAD

**Issue by garthk** [opencensus-beam/opencensus_elixir#14]
There's a copy of  `set_logger_metadata/1` found in each of:

  * `Opencensus.Plug.Trace.set_logger_metadata/1`
  * `OpencensusPhoenix.Instrumenter.set_logger_metadata/1`

… and possibly some more of the modules in this org.

@tsloughter already noted a TODO; we just need to do it.

**Comment by garthk** [comment]
This might also help educate the the thick/thin wrapper decision: forcing everyone to remember to call `set_logger_metadata/1` after `:ocp.with_child_span/1` and `:ocp.finish_span/0` strikes me as insufficiently helpful.

**Comment by garthk** [comment]
Could we also handle `:undefined` to clear out the metadata, as returned by `:ocp.current_span_ctx/0` after a `:ocp.finish_span/0` without a parent? Setting the keys to `nil` does the trick.

**Comment by garthk** [comment]
@hauleth mentioned `set_logger_metadata` might not be necessary in the near future, but I don't have a timeframe or a ticket number for that.

**Comment by hauleth** [comment]
@garthk https://github.com/elixir-lang/elixir/issues/6611

**Comment by garthk** [comment]
Thanks!

**Comment by garthk** [comment]
Fixed in #15, release TBA
