### ISSUE TITLE
Make additional attributes optional when creating a new span

### ISSUE THREAD

**Issue by tsloughter** [opencensus-beam/opencensus_elixir#3]

**Comment by hauleth** [comment]
I think this was done by e7cd2f0d1135a6cf5681a0c9913c20ba42839a5b

**Comment by tsloughter** [comment]
@hauleth oh, the title wasn't clear, this is about the inclusion of file, module, line attributes that are added automatically.

**Comment by hauleth** [comment]
Ok, I will handle that later. 

--
Łukasz Jan Niemier

**Comment by hauleth** [comment]
After second thoughts I would oppose making these attributes optional. If someone do not want them in their view then they will just ignore them. It is the same behaviour as in Erlang's `logger` and Elixir's `Logger`.

**Comment by tsloughter** [comment]
What do you mean by "view" here? Forcing inclusion of multiple attributes in a span is the same as the behaviour in a logger that gives the option to include that data in a log line.
